server:
  port: 8866
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    accesslog.enabled: false
    max-threads: 128

aarogyaSetu:
  baseUrl: https://cdn-api.co-vin.in
  availibilityPath: /api/v2/appointment/sessions/calendarByDistrict

ifttt:
  baseUrl: https://maker.ifttt.com
  #please provide the trigger function mentioned in the ifttt, refer README.
  triggerFunction:
  #please provide the key, refer README for more info.
  key: 
  triggerPath: /trigger/
  keyPath: /with/key/