server:
  port: 8866
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    accesslog.enabled: false
    max-threads: 128

aarogyaSetu:
  baseUrl: https://cdn-api.co-vin.in
  availibilityPath: /api/v2/appointment/sessions/public/calendarByDistrict
